### ISSUE TITLE
Please do a 10.1 tag on c10 branch

### ISSUE THREAD

**Issue by tdawson** [CentOS/centos-indexhtml#5]
centos-indexhtml-10.0-1.el10 was a quick and fast build to get a package out.  It doesn't have the proper tarball from here.

We would like to get a proper package created, using the correct source.
Please tag  the c10 branch.
Since what we have is already 10.0, I think it would be best if your tag had 10.1.

Thank You, and I promise for CentOS Stream 11, we'll do it the right way instead of the fast way.

**Comment by areguera** [comment]
Hey @tdawson , I opened the PR #6  to attend this issue. Would you mind to take a look at it to see if it is ok for you?

**Comment by areguera** [comment]
Tag [10.1](https://github.com/CentOS/centos-indexhtml/releases/tag/10.1) has been created on recently updated [c10](https://github.com/CentOS/centos-indexhtml/tree/c10) branch.

**Comment by tdawson** [comment]
Looks good.  Builds good.  Thank you.
